import { afterEach,expect,it,vi } from "vitest";
import { shouldShowInApp,unreadNotifications } from "./in-app-notifications";
import { encryptSecret } from "./crypto";
import type { Journey } from "./travel-planner";
afterEach(()=>vi.unstubAllEnvs());
const row=(id:string,journeyId="j",readAt:Date|null=null)=>({id,payload:JSON.stringify({journeyId}),readAt});
it("keeps one unread notification for each active journey, including legacy duplicates",()=>{const journey:Journey={id:"j",from:"A",to:"B",date:"2026-12-01",windowDays:60,originOffset:0,departure:"20:00",train:"",travelClass:"",pnr:"",notes:"",status:"needs_booking"};const jobs=[row("1"),row("2"),row("3"),row("other","k")];expect(unreadNotifications(jobs,[journey],new Date("2026-10-02T08:00:00Z")).map(j=>j.id)).toEqual(["1"]);expect(unreadNotifications(jobs,[{...journey,status:"booked"}],new Date("2026-10-02T08:00:00Z"))).toEqual([]);});
it("allows only a later scheduled reminder after dismissal, never a backlog or unread duplicate",()=>{const due=new Date("2026-10-02T01:30:00Z"),read=new Date("2026-10-01T15:00:00Z");expect(shouldShowInApp([row("1")],"j",due)).toBe(false);expect(shouldShowInApp([row("1","j",read)],"j",due)).toBe(true);expect(shouldShowInApp([row("1","j",due)],"j",due)).toBe(false);expect(shouldShowInApp([row("1","j",new Date("2026-10-02T02:00:00Z"))],"j",due)).toBe(false);expect(shouldShowInApp([row("1","other")],"j",due)).toBe(true);});
it("groups encrypted reminder payloads",()=>{vi.stubEnv("APP_ENCRYPTION_KEY",Buffer.alloc(32,4).toString("base64"));expect(shouldShowInApp([{...row("1"),payload:encryptSecret(JSON.stringify({journeyId:"j"}))}],"j",new Date())).toBe(false);});

it("shows a delivery failure once ahead of the same journey's reminder and hides dismissed failures",()=>{const journey:Journey={id:"j",from:"A",to:"B",date:"2026-12-01",windowDays:60,originOffset:0,departure:"20:00",train:"",travelClass:"",pnr:"",notes:"",status:"needs_booking"};const sent={...row("sent"),state:"SENT"},failed={...row("failed"),state:"FAILED"};const now=new Date("2026-10-02T08:00:00Z");expect(unreadNotifications([sent,failed],[journey],now).map(j=>j.id)).toEqual(["failed"]);expect(unreadNotifications([{...failed,readAt:now}],[journey],now)).toEqual([]);});
