import { decryptSecret } from "./crypto";
import { prisma } from "./db";
import { todayIST,type Journey } from "./travel-planner";
type ReminderRecord={id:string;payload:string;readAt:Date|null};
export function reminderJourneyId(payload:string){return payload?JSON.parse(decryptSecret(payload)!).journeyId as string|undefined:undefined;}
export function shouldShowInApp(history:ReminderRecord[],journeyId:string,dueAt:Date){const same=history.filter(job=>reminderJourneyId(job.payload)===journeyId);return !same.some(job=>!job.readAt||job.readAt>=dueAt);}
export function unreadNotifications<T extends ReminderRecord>(jobs:T[],journeys:Journey[],now=new Date()){const active=new Set(journeys.filter(j=>!j.archivedAt&&j.status==="needs_booking"&&j.date>=todayIST(now)).map(j=>j.id)),seen=new Set<string>();return jobs.filter(job=>{const id=reminderJourneyId(job.payload);if(job.readAt||!id||!active.has(id)||seen.has(id))return false;seen.add(id);return true;});}
export async function recordInAppReminder(job:{id:string;userId:string;lease:string;journeyId:string;dueAt:Date},now:Date){return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "User" WHERE id = ${job.userId} FOR UPDATE`;const history=await tx.railJob.findMany({where:{userId:job.userId,kind:"IN_APP",state:"SENT"},select:{id:true,payload:true,readAt:true}});const show=shouldShowInApp(history,job.journeyId,job.dueAt);const saved=await tx.railJob.updateMany({where:{id:job.id,lease:job.lease,state:"SENDING"},data:{state:show?"SENT":"SUPPRESSED",sentAt:show?now:null,lastError:null,lease:null,leaseUntil:null}});return Boolean(show&&saved.count);});}
export async function dismissInAppReminder(userId:string,id:string,now=new Date()){await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "User" WHERE id = ${userId} FOR UPDATE`;const history=await tx.railJob.findMany({where:{userId,kind:"IN_APP",state:"SENT"},select:{id:true,payload:true,readAt:true}});const target=history.find(j=>j.id===id);if(!target)return;const journeyId=reminderJourneyId(target.payload);const ids=journeyId?history.filter(j=>!j.readAt&&reminderJourneyId(j.payload)===journeyId).map(j=>j.id):[id];await tx.railJob.updateMany({where:{userId,id:{in:ids}},data:{readAt:now}});});}
