import { decryptSecret } from "./crypto";
import { prisma } from "./db";
import { todayIST,type Journey } from "./travel-planner";
type ReminderRecord={id:string;payload:string;readAt:Date|null;state?:string};
/** Extracts a journey identifier from an encrypted reminder job payload. */
export function reminderJourneyId(payload:string){return payload?JSON.parse(decryptSecret(payload)!).journeyId as string|undefined:undefined;}
/** Identifies booking versus cancellation notifications, including historical payloads. */
function reminderType(payload:string){const data=JSON.parse(decryptSecret(payload)!);return data.reminderType??(data.message?.startsWith("Cancel your ticket")?"cancellation":"booking");}
/** Filters notifications to journeys that still require action. */
export function shouldShowInApp(history:ReminderRecord[],journeyId:string,dueAt:Date,purpose="booking"){const same=history.filter(job=>reminderJourneyId(job.payload)===journeyId&&reminderType(job.payload)===purpose);return !same.some(job=>!job.readAt||job.readAt>=dueAt);}
/** Groups actionable unread reminders so each journey appears only once. */
export function unreadNotifications<T extends ReminderRecord>(jobs:T[],journeys:Journey[],now=new Date()){const active=new Map(journeys.filter(j=>!j.archivedAt&&["needs_booking","cancellation_needed"].includes(j.status)&&j.date>=todayIST(now)).map(j=>[j.id,j.status=== "cancellation_needed"?"cancellation":"booking"])),seen=new Set<string>();return [...jobs].sort((a,b)=>Number(["FAILED","MISSED"].includes(b.state??""))-Number(["FAILED","MISSED"].includes(a.state??""))).filter(job=>{const id=reminderJourneyId(job.payload);if(job.readAt||!id||active.get(id)!==reminderType(job.payload)||seen.has(id))return false;seen.add(id);return true;});}
/** Records a due reminder without duplicating an existing unread notification. */
export async function recordInAppReminder(job:{id:string;userId:string;lease:string;journeyId:string;dueAt:Date;reminderType?:string},now:Date){return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "User" WHERE id = ${job.userId} FOR UPDATE`;const history=await tx.railJob.findMany({where:{userId:job.userId,kind:"IN_APP",state:"SENT"},select:{id:true,payload:true,readAt:true}});const show=shouldShowInApp(history,job.journeyId,job.dueAt,job.reminderType);const saved=await tx.railJob.updateMany({where:{id:job.id,lease:job.lease,state:"SENDING"},data:{state:show?"SENT":"SUPPRESSED",sentAt:show?now:null,lastError:null,lease:null,leaseUntil:null}});return Boolean(show&&saved.count);});}
/** Acknowledges the journey notification and permits a later due reminder if still unbooked. */
export async function dismissInAppReminder(userId:string,id:string,now=new Date()){await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "User" WHERE id = ${userId} FOR UPDATE`;const history=await tx.railJob.findMany({where:{userId,OR:[{kind:"IN_APP",state:"SENT"},{kind:{in:["IN_APP","TELEGRAM","WHATSAPP","EMAIL","PUSH"]},state:{in:["FAILED","MISSED"]}}]},select:{id:true,payload:true,readAt:true}});const target=history.find(j=>j.id===id);if(!target)return;const journeyId=reminderJourneyId(target.payload);const ids=journeyId?history.filter(j=>!j.readAt&&reminderJourneyId(j.payload)===journeyId).map(j=>j.id):[id];await tx.railJob.updateMany({where:{userId,id:{in:ids}},data:{readAt:now}});});}
