import {bookingDay,formatDay,type Journey} from "./travel-planner";
/** Escapes dynamic email text and attribute values. */
function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));}
/** Builds a branded inline-styled email and its accessible plain-text fallback. */
export function emailTemplate(title:string,text:string,action?:{label:string;url:string}){
 const url=action&&/^https?:$/.test(new URL(action.url).protocol)?action.url:undefined;
 const content=text.split("\n\n").filter(p=>p.trim()).map(p=>`<p style="line-height:1.7;color:#485166">${escapeHtml(p).replaceAll("\n","<br>")}</p>`).join("");
 const button=url?`<table role="presentation"><tr><td bgcolor="#c4adff" style="border-radius:10px"><a href="${escapeHtml(url)}" style="display:inline-block;padding:14px 22px;color:#20172e;text-decoration:none;font-weight:bold">${escapeHtml(action!.label)}</a></td></tr></table><p style="font-size:12px;color:#677086">If the button does not work, copy this link:<br><a href="${escapeHtml(url)}" style="color:#6650a0;word-break:break-all">${escapeHtml(url)}</a></p>`:"";
 return {text,html:`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title></head><body style="margin:0;background:#f1f2f7;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px"><tr><td style="background:#191e29;color:white;padding:26px 30px;border-radius:16px 16px 0 0"><span style="font-size:26px;font-weight:bold">RailWatch</span><br><span style="color:#c4adff;font-size:13px">Your journeys. Right on time.</span></td></tr><tr><td style="background:white;padding:30px;border-radius:0 0 16px 16px"><h1 style="color:#202735;font-size:24px">${escapeHtml(title)}</h1>${content}${button}</td></tr><tr><td style="padding:22px;color:#677086;font-size:12px;text-align:center">Sent by your RailWatch instance.<br>Book and cancel tickets through IRCTC.</td></tr></table></td></tr></table></body></html>`};
}
/** Formats booking details for Telegram without ticket or passenger identifiers. */
export function telegramBookingMessage(j:Journey){return `🚆 RailWatch · Booking Reminder\n\n${j.from} → ${j.to}\n\n🗓 Travel: ${formatDay(j.date,{day:"numeric",month:"long",year:"numeric"})}\n🎟 Booking: ${formatDay(bookingDay(j),{day:"numeric",month:"long",year:"numeric"})}\n🕗 Opens at 8:00 AM IST\n\nBook through IRCTC, then mark this journey as booked in RailWatch.`;}
