import { randomUUID } from "node:crypto";
import { describe,it,expect,afterEach,vi } from "vitest";
import { prisma } from "./db";
import { loadWorkspace,saveWorkspace } from "./railplan-store";
import { encryptSecret } from "./crypto";
import { processRailplan } from "./railplan-jobs";
import { addDays,EMPTY_PLANNER,todayIST,type Journey,type Rule } from "./travel-planner";
vi.mock("./railplan-google",()=>({syncGoogleCalendars:async()=>0}));
const users:string[]=[];
async function fixture(){if(!new URL(process.env.DATABASE_URL!).pathname.endsWith("_test"))throw new Error("Use an isolated test database.");const u=await prisma.user.create({data:{email:`${randomUUID()}@railplan.invalid`}});users.push(u.id);return {user:u,...await loadWorkspace(u.id)};}
afterEach(async()=>{if(users.length)await prisma.user.deleteMany({where:{id:{in:users.splice(0)}}});});
describe.skipIf(process.env.RUN_DB_TESTS!=="1")("account-backed RailWatch",()=>{
  it("stores encrypted plans and rejects stale concurrent writes",async()=>{const {user,planner,revision}=await fixture();const edits=await Promise.allSettled([saveWorkspace(user.id,{...planner,settings:{...planner.settings,theme:"dark"}},revision),saveWorkspace(user.id,{...planner,settings:{...planner.settings,bookingWindowDays:45}},revision)]);expect(edits.filter(e=>e.status==="fulfilled")).toHaveLength(1);const row=await prisma.railWorkspace.findUniqueOrThrow({where:{userId:user.id}});expect(row.payload).toMatch(/^enc:v1:/);expect(row.payload).not.toContain("settings");expect(row.version).toBe(2);});
  it("does not accept attachments owned by another account",async()=>{const a=await fixture(),b=await fixture();const date=todayIST();const attachment={id:"ticket",name:"ticket.pdf",type:"application/pdf" as const,size:5,createdAt:new Date().toISOString()};await prisma.railFile.create({data:{id:attachment.id,userId:a.user.id,name:attachment.name,type:attachment.type,size:5,payload:encryptSecret("JVBERi0=")}});const journey:Journey={id:"j",from:"A",to:"B",date,departure:"20:00",train:"",pnr:"",travelClass:"",windowDays:60,originOffset:0,status:"booked",notes:"",attachments:[attachment]};await expect(saveWorkspace(b.user.id,{...EMPTY_PLANNER,journeys:[journey]},b.revision)).rejects.toThrow("Upload the original");expect((await loadWorkspace(b.user.id)).revision).toBe(1);});
  it("extends ongoing routines without a browser and avoids duplicate reminder deliveries",async()=>{const {user,planner,revision}=await fixture();const today=todayIST();const rule:Rule={id:"routine",name:"Daily",from:"A",to:"B",start:today,end:null,weekdays:[0],intervalWeeks:1,recurrence:{frequency:"daily",interval:1,monthlyPattern:"date",dayOfMonth:1,ordinal:1,weekday:0},paused:false,excludedDates:[],departure:"20:00",returnDeparture:"20:00",returnAfterDays:null,returnTrain:"",returnOriginOffset:0,train:"",travelClass:"",originOffset:0,windowDays:60};const journey:Journey={id:"due",from:"C",to:"D",date:addDays(today,60),departure:"20:00",train:"",pnr:"",travelClass:"",windowDays:60,originOffset:0,status:"needs_booking",notes:""};await saveWorkspace(user.id,{...planner,rules:[rule],journeys:[journey]},revision);const now=new Date(`${today}T08:00:00+05:30`);await Promise.all([processRailplan(now),processRailplan(now)]);const loaded=await loadWorkspace(user.id);expect(loaded.planner.journeys.length).toBeGreaterThan(180);const jobs=await prisma.railJob.findMany({where:{userId:user.id,state:"SENT"}});expect(jobs.length).toBeGreaterThan(0);expect(new Set(jobs.map(j=>j.key)).size).toBe(jobs.length);await processRailplan(now);expect(await prisma.railJob.count({where:{userId:user.id,state:"SENT"}})).toBe(jobs.length);},20000);
  it("reactivates pending reminders when a journey returns to To book",async()=>{const f=await fixture();const today=todayIST();const now=new Date(today+'T08:00:00+05:30');let current=await saveWorkspace(f.user.id,{...f.planner,journeys:[{id:"return-to-book",from:"A",to:"B",date:addDays(today,65),departure:"20:00",train:"",pnr:"",travelClass:"",windowDays:60,originOffset:0,status:"needs_booking",notes:""}]},f.revision);await processRailplan(now);const pending=await prisma.railJob.count({where:{userId:f.user.id,state:"PENDING"}});expect(pending).toBeGreaterThan(0);current.planner.journeys[0].status="booked";current=await saveWorkspace(f.user.id,current.planner,current.revision);await processRailplan(now);expect(await prisma.railJob.count({where:{userId:f.user.id,state:"CANCELLED"}})).toBe(pending);current.planner.journeys[0].status="needs_booking";await saveWorkspace(f.user.id,current.planner,current.revision);await processRailplan(now);expect(await prisma.railJob.count({where:{userId:f.user.id,state:"PENDING"}})).toBe(pending);});
});
