import { dismissInAppReminder,recordInAppReminder } from "./in-app-notifications";
import { receiveTelegramUpdate,tokenHash,telegramChatHash } from "./telegram";
import type { TelegramConfiguration } from "./provider-config";
import { decryptSecret } from "./crypto";
import { randomUUID } from "node:crypto";
import { describe,it,expect,afterEach,vi } from "vitest";
import { prisma } from "./db";
import { loadWorkspace,saveWorkspace } from "./railplan-store";
import { encryptSecret } from "./crypto";
import { processRailplan } from "./railplan-jobs";
import { addDays,EMPTY_PLANNER,todayIST,type Journey,type Rule } from "./travel-planner";
vi.mock("./railplan-google",()=>({syncGoogleCalendars:async()=>0}));
const users:string[]=[];
async function fixture(){if(!new URL(process.env.DATABASE_URL!).pathname.endsWith("_test"))throw new Error("Use an isolated test database.");await prisma.appSettings.upsert({where:{id:"global"},create:{id:"global"},update:{bookingWindowDays:60,remindersEnabled:true,whatsappEnabled:true}});const u=await prisma.user.create({data:{email:`${randomUUID()}@railplan.invalid`}});users.push(u.id);return {user:u,...await loadWorkspace(u.id)};}
afterEach(async()=>{if(users.length)await prisma.user.deleteMany({where:{id:{in:users.splice(0)}}});});
describe.skipIf(process.env.RUN_DB_TESTS!=="1")("account-backed RailWatch",()=>{
  it("stores encrypted plans and rejects stale concurrent writes",async()=>{const {user,planner,revision}=await fixture();const edits=await Promise.allSettled([saveWorkspace(user.id,{...planner,settings:{...planner.settings,theme:"dark"}},revision),saveWorkspace(user.id,{...planner,settings:{...planner.settings,bookingWindowDays:45}},revision)]);expect(edits.filter(e=>e.status==="fulfilled")).toHaveLength(1);const row=await prisma.railWorkspace.findUniqueOrThrow({where:{userId:user.id}});expect(row.payload).toMatch(/^enc:v1:/);expect(row.payload).not.toContain("settings");expect(row.version).toBe(2);});
  it("does not accept attachments owned by another account",async()=>{const a=await fixture(),b=await fixture();const date=todayIST();const attachment={id:"ticket",name:"ticket.pdf",type:"application/pdf" as const,size:5,createdAt:new Date().toISOString()};await prisma.railFile.create({data:{id:attachment.id,userId:a.user.id,name:attachment.name,type:attachment.type,size:5,payload:encryptSecret("JVBERi0=")}});const journey:Journey={id:"j",from:"A",to:"B",date,departure:"20:00",train:"",pnr:"",travelClass:"",windowDays:60,originOffset:0,status:"booked",notes:"",attachments:[attachment]};await expect(saveWorkspace(b.user.id,{...EMPTY_PLANNER,journeys:[journey]},b.revision)).rejects.toThrow("Upload the original");expect((await loadWorkspace(b.user.id)).revision).toBe(1);});
  it("extends ongoing routines without a browser and avoids duplicate reminder deliveries",async()=>{const {user,planner,revision}=await fixture();const today=todayIST();const rule:Rule={id:"routine",name:"Daily",from:"A",to:"B",start:today,end:null,weekdays:[0],intervalWeeks:1,recurrence:{frequency:"daily",interval:1,monthlyPattern:"date",dayOfMonth:1,ordinal:1,weekday:0},paused:false,excludedDates:[],departure:"20:00",returnDeparture:"20:00",returnAfterDays:null,returnTrain:"",returnOriginOffset:0,train:"",travelClass:"",originOffset:0,windowDays:60};const journey:Journey={id:"due",from:"C",to:"D",date:addDays(today,60),departure:"20:00",train:"",pnr:"",travelClass:"",windowDays:60,originOffset:0,status:"needs_booking",notes:""};await saveWorkspace(user.id,{...planner,rules:[rule],journeys:[journey]},revision);const now=new Date(`${today}T08:00:00+05:30`);await Promise.all([processRailplan(now),processRailplan(now)]);const loaded=await loadWorkspace(user.id);expect(loaded.planner.journeys.length).toBeGreaterThan(180);const jobs=await prisma.railJob.findMany({where:{userId:user.id,state:"SENT"}});expect(jobs.length).toBeGreaterThan(0);expect(new Set(jobs.map(j=>j.key)).size).toBe(jobs.length);await processRailplan(now);expect(await prisma.railJob.count({where:{userId:user.id,state:"SENT"}})).toBe(jobs.length);},20000);
  it("reactivates pending reminders when a journey returns to To book",async()=>{const f=await fixture();const today=todayIST();const now=new Date(today+'T08:00:00+05:30');let current=await saveWorkspace(f.user.id,{...f.planner,journeys:[{id:"return-to-book",from:"A",to:"B",date:addDays(today,65),departure:"20:00",train:"",pnr:"",travelClass:"",windowDays:60,originOffset:0,status:"needs_booking",notes:""}]},f.revision);await processRailplan(now);const pending=await prisma.railJob.count({where:{userId:f.user.id,state:"PENDING"}});expect(pending).toBeGreaterThan(0);current.planner.journeys[0].status="booked";current=await saveWorkspace(f.user.id,current.planner,current.revision);await processRailplan(now);expect(await prisma.railJob.count({where:{userId:f.user.id,state:"CANCELLED"}})).toBe(pending);current.planner.journeys[0].status="needs_booking";await saveWorkspace(f.user.id,current.planner,current.revision);await processRailplan(now);expect(await prisma.railJob.count({where:{userId:f.user.id,state:"PENDING"}})).toBe(pending);});
  it("applies shared booking rules and account phones, and pauses worker reminders when disabled",async()=>{
    const f=await fixture();const previous=await prisma.appSettings.findUniqueOrThrow({where:{id:"global"}});
    try{
      await prisma.user.update({where:{id:f.user.id},data:{phoneNumber:"+919876543210"}});
      await prisma.appSettings.update({where:{id:"global"},data:{bookingWindowDays:45,remindersEnabled:false,whatsappEnabled:false}});
      const current=await loadWorkspace(f.user.id);const today=todayIST();
      const saved=await saveWorkspace(f.user.id,{...current.planner,settings:{...current.planner.settings,bookingWindowDays:300,whatsappNumber:"+441234567890"},journeys:[{id:"paused",from:"A",to:"B",date:addDays(today,45),departure:"20:00",train:"",pnr:"",travelClass:"",windowDays:300,originOffset:0,status:"needs_booking",notes:""}]},current.revision);
      expect(saved.planner.settings.whatsappNumber).toBe("+919876543210");expect(saved.planner.journeys[0].windowDays).toBe(45);
      await processRailplan(new Date(today+"T08:00:00+05:30"));expect(await prisma.railJob.count({where:{userId:f.user.id,state:"SENT"}})).toBe(0);
      await prisma.appSettings.update({where:{id:"global"},data:{remindersEnabled:true}});
      await processRailplan(new Date(today+"T08:00:00+05:30"));expect(await prisma.railJob.count({where:{userId:f.user.id,state:"SENT"}})).toBeGreaterThan(0);
    }finally{await prisma.appSettings.update({where:{id:"global"},data:{bookingWindowDays:previous.bookingWindowDays,remindersEnabled:previous.remindersEnabled,whatsappEnabled:previous.whatsappEnabled}});}
  });

});

describe.skipIf(process.env.RUN_DB_TESTS!=="1")("Telegram account connections",()=>{
 it("accepts private one-time links, rejects expired/replayed/group links, and stops reminders",async()=>{
  const f=await fixture(),other=await fixture(),settings=await prisma.appSettings.findUniqueOrThrow({where:{id:"global"}});
  const bot:TelegramConfiguration={botToken:"123456789:"+"a".repeat(35),botUsername:"RailWatchBot",id:"test-bot",webhookSecret:"test-secret",webhookReady:true};
  const token="a".repeat(43),chatId=123456789;const update={update_id:1,message:{text:"/start "+token,chat:{id:chatId,type:"private"},from:{id:chatId,is_bot:false,username:"traveler"}}};
  try{
   await prisma.appSettings.update({where:{id:"global"},data:{telegramEnabled:true,remindersEnabled:true,providerConfig:encryptSecret(JSON.stringify({telegram:bot}))}});
   await prisma.railTelegram.create({data:{userId:f.user.id,providerId:bot.id,linkTokenHash:tokenHash(token),linkExpiresAt:new Date(Date.now()+60000)}});
   expect(await receiveTelegramUpdate({...update,message:{...update.message,chat:{id:chatId,type:"group"}}},bot)).toBeNull();
   expect(await receiveTelegramUpdate({...update,message:{...update.message,from:{id:chatId+1}}},bot)).toBeNull();
   expect(await receiveTelegramUpdate(update,bot)).toMatchObject({method:"sendMessage",chat_id:String(chatId)});
   const stored=await prisma.railTelegram.findUniqueOrThrow({where:{userId:f.user.id}});expect(stored.chatId).toMatch(/^enc:v1:/);expect(decryptSecret(stored.chatId)).toBe(String(chatId));expect(stored.linkTokenHash).toBeNull();expect(await receiveTelegramUpdate(update,bot)).toBeNull();
   const loaded=await loadWorkspace(f.user.id);expect(loaded.planner.settings.telegramEnabled).toBe(true);expect((await loadWorkspace(other.user.id)).planner.settings.telegramChatId).toBe("");
   const forged=await loadWorkspace(other.user.id);const saved=await saveWorkspace(other.user.id,{...forged.planner,settings:{...forged.planner.settings,telegramEnabled:true,telegramChatId:String(chatId),telegramProviderId:bot.id}},forged.revision);expect(saved.planner.settings.telegramEnabled).toBe(false);expect(saved.planner.settings.telegramChatId).toBe("");
   await prisma.railTelegram.create({data:{userId:other.user.id,providerId:bot.id,linkTokenHash:tokenHash("b".repeat(43)),linkExpiresAt:new Date(Date.now()-1000)}});expect(await receiveTelegramUpdate({...update,message:{...update.message,text:"/start "+"b".repeat(43)}},bot)).toBeNull();
   await prisma.railTelegram.update({where:{userId:other.user.id},data:{linkExpiresAt:new Date(Date.now()+60000)}});expect(await receiveTelegramUpdate({...update,message:{...update.message,text:"/start "+"b".repeat(43)}},bot)).toBeNull();
   expect(await receiveTelegramUpdate({...update,message:{...update.message,text:"/stop"}},bot)).toMatchObject({method:"sendMessage"});expect((await loadWorkspace(f.user.id)).planner.settings.telegramEnabled).toBe(false);
   expect(await receiveTelegramUpdate(update,{...bot,id:"rotated"})).toBeNull();
   await prisma.railTelegram.update({where:{userId:f.user.id},data:{enabled:true}});await prisma.appSettings.update({where:{id:"global"},data:{telegramEnabled:false}});expect((await loadWorkspace(f.user.id)).planner.settings.telegramEnabled).toBe(false);
  }finally{await prisma.appSettings.update({where:{id:"global"},data:{providerConfig:settings.providerConfig,telegramEnabled:settings.telegramEnabled,remindersEnabled:settings.remindersEnabled}});}
 });
 it("delivers scheduled Telegram messages once and cancels future reminders after disconnect",async()=>{
  const f=await fixture(),settings=await prisma.appSettings.findUniqueOrThrow({where:{id:"global"}});const bot:TelegramConfiguration={botToken:"123456789:"+"a".repeat(35),botUsername:"RailWatchBot",id:"delivery-bot",webhookSecret:"test-secret",webhookReady:true};const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({ok:true,result:{message_id:42}})});vi.stubGlobal("fetch",fetch);
  try{await prisma.appSettings.update({where:{id:"global"},data:{telegramEnabled:true,remindersEnabled:true,providerConfig:encryptSecret(JSON.stringify({telegram:bot}))}});await prisma.railTelegram.create({data:{userId:f.user.id,providerId:bot.id,enabled:true,chatId:encryptSecret("123456789"),chatHash:telegramChatHash(bot.id,"123456789")}});const today=todayIST(),now=new Date(today+"T08:00:00+05:30"),current=await loadWorkspace(f.user.id);await saveWorkspace(f.user.id,{...current.planner,journeys:[{id:"telegram-delivery",from:"A",to:"B",date:addDays(today,60),departure:"20:00",train:"",travelClass:"",windowDays:60,originOffset:0,status:"needs_booking",pnr:"",notes:""}]},current.revision);await processRailplan(now);const sent=fetch.mock.calls.length;expect(sent).toBeGreaterThan(0);expect(fetch.mock.calls.every(call=>new URL(call[0]).hostname === "api.telegram.org")).toBe(true);await processRailplan(now);expect(fetch).toHaveBeenCalledTimes(sent);await prisma.railTelegram.delete({where:{userId:f.user.id}});expect((await loadWorkspace(f.user.id)).planner.settings.telegramEnabled).toBe(false);
  }finally{vi.unstubAllGlobals();await prisma.appSettings.update({where:{id:"global"},data:{providerConfig:settings.providerConfig,telegramEnabled:settings.telegramEnabled,remindersEnabled:settings.remindersEnabled}});}
 });
});

describe.skipIf(process.env.RUN_DB_TESTS!=="1")("in-app notification lifecycle",()=>{
 it("serializes duplicate reminders, dismisses the journey, and allows only a later reminder",async()=>{const f=await fixture(),due=new Date("2026-10-02T01:30:00Z");async function job(key:string){return prisma.railJob.create({data:{userId:f.user.id,key,kind:"IN_APP",state:"SENDING",lease:key,dueAt:due,payload:encryptSecret(JSON.stringify({journeyId:"same",message:"Book"}))}});}const a=await job("first"),b=await job("duplicate");const results=await Promise.all([a,b].map(j=>recordInAppReminder({id:j.id,userId:f.user.id,lease:j.lease!,journeyId:"same",dueAt:due},due)));expect(results.filter(Boolean)).toHaveLength(1);expect(await prisma.railJob.count({where:{userId:f.user.id,kind:"IN_APP",state:"SENT",readAt:null}})).toBe(1);const notification=await prisma.railJob.findFirstOrThrow({where:{userId:f.user.id,state:"SENT"}});const dismissed=new Date("2026-10-02T02:00:00Z");await dismissInAppReminder(f.user.id,notification.id,dismissed);const backlog=await job("backlog");expect(await recordInAppReminder({id:backlog.id,userId:f.user.id,lease:backlog.lease!,journeyId:"same",dueAt:due},dismissed)).toBe(false);const later=await job("later");expect(await recordInAppReminder({id:later.id,userId:f.user.id,lease:later.lease!,journeyId:"same",dueAt:new Date("2026-10-02T02:30:00Z")},new Date("2026-10-02T02:30:00Z"))).toBe(true);const other=await fixture();await dismissInAppReminder(other.user.id,later.id);expect(await prisma.railJob.count({where:{userId:f.user.id,state:"SENT",readAt:null}})).toBe(1);});
 it("dismisses all historical duplicates for the same journey",async()=>{const f=await fixture();await prisma.railJob.createMany({data:["old1","old2","old3"].map(key=>({userId:f.user.id,key,kind:"IN_APP",state:"SENT",dueAt:new Date(),payload:encryptSecret(JSON.stringify({journeyId:"legacy"}))}))});const first=await prisma.railJob.findFirstOrThrow({where:{userId:f.user.id}});await dismissInAppReminder(f.user.id,first.id);expect(await prisma.railJob.count({where:{userId:f.user.id,kind:"IN_APP",state:"SENT",readAt:null}})).toBe(0);});
});
