import { afterEach,expect,it,vi } from "vitest";
import { createLocalJWKSet,exportJWK,generateKeyPair,SignJWT } from "jose";
import { authorizationDetails,verifyTelegramIdentity } from "./telegram-login";
import { providerSummary,updateProviderConfiguration,type TelegramConfiguration } from "./provider-config";
const bot:TelegramConfiguration={botToken:"123456789:"+"a".repeat(35),botUsername:"RailWatchBot",id:"bot",webhookSecret:"secret",webhookReady:true,clientId:"123456789",clientSecret:"login-secret"};
afterEach(()=>vi.unstubAllEnvs());
it("uses a fixed authorization origin, PKCE, state, nonce, and only required scopes",()=>{vi.stubEnv("APP_URL","https://railwatch.example");const a=authorizationDetails(bot),b=authorizationDetails(bot),url=new URL(a.url);expect(url.origin).toBe("https://oauth.telegram.org");expect(url.searchParams.get("scope")).toBe("openid profile telegram:bot_access");expect(url.searchParams.get("redirect_uri")).toBe("https://railwatch.example/api/railwatch/telegram/callback");expect(url.searchParams.get("code_challenge_method")).toBe("S256");expect(a.state).not.toBe(b.state);expect(a.verifier).not.toBe(b.verifier);expect(url.searchParams.get("code_challenge")).not.toBe(a.verifier);});
it("verifies signatures and rejects wrong audience, issuer, nonce, expiration, and identity",async()=>{
 const {publicKey,privateKey}=await generateKeyPair("RS256"),key=createLocalJWKSet({keys:[{...await exportJWK(publicKey),kid:"test",alg:"RS256"}]}),now=Math.floor(Date.now()/1000);
 async function signed(patch:Record<string,unknown>={}){return new SignJWT({sub:"1234123412341234123",id:12345,nonce:"nonce",iss:"https://oauth.telegram.org",aud:bot.clientId,iat:now,exp:now+300,...patch}).setProtectedHeader({alg:"RS256",kid:"test"}).sign(privateKey);}
 expect(await verifyTelegramIdentity(await signed(),bot,"nonce",key)).toEqual({chatId:"12345",username:null});
 for(const patch of [{aud:"other"},{iss:"https://evil.example"},{nonce:"other"},{exp:now-1},{id:null},{id:Number.MAX_SAFE_INTEGER+1},{sub:""}])await expect(verifyTelegramIdentity(await signed(patch),bot,"nonce",key)).rejects.toThrow();
 const rogue=await generateKeyPair("RS256");const bad=await new SignJWT({}).setProtectedHeader({alg:"RS256",kid:"test"}).sign(rogue.privateKey);await expect(verifyTelegramIdentity(bad,bot,"nonce",key)).rejects.toThrow();
});
it("stores login credentials encrypted and does not expose the secret or disconnect users on login-only changes",()=>{vi.stubEnv("APP_ENCRYPTION_KEY",Buffer.alloc(32,4).toString("base64"));const saved=updateProviderConfiguration({telegram:bot},{telegram:{botUsername:bot.botUsername,clientId:bot.clientId,clientSecret:"new-login-secret"}});expect(saved.telegramChanged).toBe(false);expect(saved.payload).not.toContain("new-login-secret");expect(JSON.stringify(providerSummary(saved.next))).not.toContain("new-login-secret");expect(providerSummary(saved.next).telegram.loginConfigured).toBe(true);expect(updateProviderConfiguration(saved.next,{telegram:{botUsername:bot.botUsername,clearLogin:true}}).next.telegram?.clientSecret).toBeUndefined();expect(()=>updateProviderConfiguration({telegram:bot},{telegram:{botUsername:bot.botUsername,clientId:"987654321"}})).toThrow();});
