import { getProviderConfiguration,googleConfigured,resolveProviderConfiguration } from "@/lib/provider-config";
import { getFeaturePolicy } from "@/lib/settings";
import { cookies } from "@/backend/context";
import { timingSafeEqual } from "node:crypto";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { decryptSecret,encryptSecret } from "@/lib/crypto";
import { googleRedirect } from "@/lib/railplan-google";
export async function GET(request:Request){const result=new URL("/",process.env.APP_URL??request.url);try{const user=await requireUser();const config=await getProviderConfiguration();const google=config.google;if(!(await getFeaturePolicy()).googleCalendarEnabled||!googleConfigured(config)||!google)throw new Error("Not configured");const jar=await cookies();const raw=jar.get("railwatch_oauth")?.value;jar.set("railwatch_oauth","",{path:"/api/railwatch/google",maxAge:0});if(!raw)throw new Error("Missing state");const saved=JSON.parse(decryptSecret(raw)!);const url=new URL(request.url);const state=url.searchParams.get("state")??"";if(saved.userId!==user.id||saved.providerId!==google.id||state.length!==43||typeof saved.state!=="string"||saved.state.length!==43||Buffer.byteLength(state)!==Buffer.byteLength(saved.state)||!timingSafeEqual(Buffer.from(state),Buffer.from(saved.state))||!url.searchParams.get("code"))throw new Error("Invalid state");const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:google.clientId,client_secret:google.clientSecret,redirect_uri:googleRedirect(),code:url.searchParams.get("code")!,code_verifier:saved.verifier,grant_type:"authorization_code"}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error("Token exchange failed");const tokens=await response.json();if(!tokens.refresh_token)throw new Error("Offline access required");await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "AppSettings" WHERE id='global' FOR UPDATE`;const current=await tx.appSettings.findUniqueOrThrow({where:{id:"global"}});if(!current.googleCalendarEnabled||resolveProviderConfiguration(current.providerConfig).google?.id!==google.id)throw new Error("Configuration changed");const existing=await tx.railGoogle.findUnique({where:{userId:user.id}});const keepCalendar=existing&&JSON.parse(decryptSecret(existing.tokens)!).providerId===google.id;const data={...(keepCalendar?{}:{calendarId:null,eventIds:[]}),tokens:encryptSecret(JSON.stringify({...tokens,providerId:google.id,expiresAt:Date.now()+tokens.expires_in*1000})),enabled:true,lastError:null,lease:null,leaseUntil:null,syncedAt:null};await tx.railGoogle.upsert({where:{userId:user.id},create:{userId:user.id,...data},update:data});});result.searchParams.set("google","connected");}catch{result.searchParams.set("google","failed");}return Response.redirect(result,303);}
