// Generated by scripts/build-backend.mjs.
import * as r0 from "./routes/admin/providers/route";
import * as r1 from "./routes/admin/providers/telegram/route";
import * as r2 from "./routes/admin/settings/route";
import * as r3 from "./routes/admin/users/[id]/route";
import * as r4 from "./routes/admin/users/route";
import * as r5 from "./routes/auth/forgot-password/route";
import * as r6 from "./routes/auth/login/route";
import * as r7 from "./routes/auth/logout/route";
import * as r8 from "./routes/auth/reset-password/route";
import * as r9 from "./routes/auth/session/route";
import * as r10 from "./routes/auth/signup/route";
import * as r11 from "./routes/health/live/route";
import * as r12 from "./routes/health/ready/route";
import * as r13 from "./routes/internal/railwatch/process/route";
import * as r14 from "./routes/railwatch/connections/route";
import * as r15 from "./routes/railwatch/files/[id]/route";
import * as r16 from "./routes/railwatch/google/callback/route";
import * as r17 from "./routes/railwatch/google/connect/route";
import * as r18 from "./routes/railwatch/profile/route";
import * as r19 from "./routes/railwatch/telegram/callback/route";
import * as r20 from "./routes/railwatch/telegram/route";
import * as r21 from "./routes/railwatch/workspace/route";
import * as r22 from "./routes/version/route";
type Handler = (request: Request, context: {params: Promise<Record<string,string>>}) => Response | Promise<Response>;
export const routes = [
{ method: "GET" as const, path: "/api/admin/providers", handler: r0.GET as Handler },
{ method: "PATCH" as const, path: "/api/admin/providers", handler: r0.PATCH as Handler },
{ method: "POST" as const, path: "/api/admin/providers/telegram", handler: r1.POST as Handler },
{ method: "GET" as const, path: "/api/admin/settings", handler: r2.GET as Handler },
{ method: "PATCH" as const, path: "/api/admin/settings", handler: r2.PATCH as Handler },
{ method: "PATCH" as const, path: "/api/admin/users/:id", handler: r3.PATCH as Handler },
{ method: "POST" as const, path: "/api/admin/users/:id", handler: r3.POST as Handler },
{ method: "GET" as const, path: "/api/admin/users", handler: r4.GET as Handler },
{ method: "POST" as const, path: "/api/admin/users", handler: r4.POST as Handler },
{ method: "POST" as const, path: "/api/auth/forgot-password", handler: r5.POST as Handler },
{ method: "POST" as const, path: "/api/auth/login", handler: r6.POST as Handler },
{ method: "POST" as const, path: "/api/auth/logout", handler: r7.POST as Handler },
{ method: "POST" as const, path: "/api/auth/reset-password", handler: r8.POST as Handler },
{ method: "GET" as const, path: "/api/auth/session", handler: r9.GET as Handler },
{ method: "POST" as const, path: "/api/auth/signup", handler: r10.POST as Handler },
{ method: "GET" as const, path: "/api/health/live", handler: r11.GET as Handler },
{ method: "GET" as const, path: "/api/health/ready", handler: r12.GET as Handler },
{ method: "POST" as const, path: "/api/internal/railwatch/process", handler: r13.POST as Handler },
{ method: "GET" as const, path: "/api/railwatch/connections", handler: r14.GET as Handler },
{ method: "POST" as const, path: "/api/railwatch/connections", handler: r14.POST as Handler },
{ method: "GET" as const, path: "/api/railwatch/files/:id", handler: r15.GET as Handler },
{ method: "PUT" as const, path: "/api/railwatch/files/:id", handler: r15.PUT as Handler },
{ method: "DELETE" as const, path: "/api/railwatch/files/:id", handler: r15.DELETE as Handler },
{ method: "GET" as const, path: "/api/railwatch/google/callback", handler: r16.GET as Handler },
{ method: "POST" as const, path: "/api/railwatch/google/connect", handler: r17.POST as Handler },
{ method: "GET" as const, path: "/api/railwatch/profile", handler: r18.GET as Handler },
{ method: "PATCH" as const, path: "/api/railwatch/profile", handler: r18.PATCH as Handler },
{ method: "GET" as const, path: "/api/railwatch/telegram/callback", handler: r19.GET as Handler },
{ method: "POST" as const, path: "/api/railwatch/telegram", handler: r20.POST as Handler },
{ method: "GET" as const, path: "/api/railwatch/workspace", handler: r21.GET as Handler },
{ method: "PUT" as const, path: "/api/railwatch/workspace", handler: r21.PUT as Handler },
{ method: "GET" as const, path: "/api/version", handler: r22.GET as Handler }
];
