"use client";
import type { FeaturePolicy } from "@/lib/feature-policy";
import { useEffect,useState } from "react";
import { apiRequest } from "@/lib/client-api";
import type { Planner } from "@/lib/travel-planner";
import s from "./planner.module.css";
type Status={whatsappReady:boolean;googleReady:boolean;google:{enabled:boolean;syncedAt:string|null;lastError:string|null;calendarId:string|null}|null;jobs:{id:string;kind:string;state:string;sentAt:string|null;lastError:string|null;message?:string;journeyId?:string;readAt?:string|null}[]};
export function Connections({planner,revision=0,commit,fail,notice,settings=true,open=()=>{},policy}:{planner:Planner;policy:FeaturePolicy;revision?:number;commit:(next:Planner,message:string)=>Promise<boolean>;fail:(message:string)=>void;notice:(message:string)=>void;settings?:boolean;open?:(id:string)=>void}){
  const [status,setStatus]=useState<Status>();const [busy,setBusy]=useState(false);
  useEffect(()=>{let live=true;const refresh=()=>apiRequest<Status>("/api/railwatch/connections",{cache:"no-store"}).then(v=>{if(live)setStatus(v);}).catch(()=>{});void refresh();const timer=setInterval(refresh,30000);return()=>{live=false;clearInterval(timer);};},[revision]);
  async function google(){setBusy(true);try{const data=await apiRequest<{url:string}>("/api/railwatch/google/connect",{method:"POST"});location.assign(data.url);}catch(e){fail(e instanceof Error?e.message:"Could not connect Google.");setBusy(false);}}
  if(!settings)return <>{status?.jobs.some(j=>j.kind==="IN_APP"&&j.state==="SENT"&&!j.readAt)&&<details className={s.reminderInbox}><summary>Booking reminders</summary>{status.jobs.filter(j=>j.kind==="IN_APP"&&j.state==="SENT"&&!j.readAt).map(j=><div className={s.fileRow} key={j.id}><span>{j.message}</span><button className={s.textButton} onClick={()=>{if(j.journeyId)open(j.journeyId);}}>View journey</button><button className={s.textButton} onClick={async()=>{try{await apiRequest("/api/railwatch/connections",{method:"POST",body:JSON.stringify({readId:j.id})});setStatus({...status,jobs:status.jobs.map(old=>old.id===j.id?{...old,readAt:new Date().toISOString()}:old)});}catch(e){fail(e instanceof Error?e.message:"Could not mark reminder read.");}}}>Mark as read</button></div>)}</details>}</>;
  return <section className={s.connections}><h2>Connections</h2><div className={s.settingsGrid}>{policy.remindersEnabled&&policy.whatsappEnabled&&<div className={s.settingsCard}><h3>WhatsApp Reminders</h3><p className={s.help}>{status?.whatsappReady?"WhatsApp is configured. Enable reminders to your saved number.":"Waiting for the administrator to add WhatsApp credentials and an approved reminder template. In-app reminders remain available."}</p><label className={s.check}><input type="checkbox" checked={planner.settings.whatsappEnabled} disabled={busy||!status?.whatsappReady||!planner.settings.whatsappNumber} onChange={async e=>{setBusy(true);await commit({...planner,settings:{...planner.settings,whatsappEnabled:e.target.checked}},e.target.checked?"WhatsApp reminders enabled.":"WhatsApp reminders disabled.");setBusy(false);}}/>Send booking reminders to my WhatsApp number</label><small className={s.help}>Uses the phone number in your Profile tab.</small></div>}{policy.googleCalendarEnabled&&<div className={s.settingsCard}><h3>Google Calendar</h3><p className={s.help}>{status?.google?status.google.enabled?"Connected. Your journeys, booking dates, and time off sync to a dedicated RailWatch calendar.":"Calendar sync is paused. Existing events remain in Google Calendar.":status?.googleReady?"Connect your Google account to keep a dedicated RailWatch calendar up to date.":"Google Calendar setup is not configured yet."}</p>{status?.google?.syncedAt&&<p className={s.help}>Last synced: {new Date(status.google.syncedAt).toLocaleString()}</p>}{status?.google?.lastError&&<p role="alert">{status.google.lastError}</p>}<div className={s.cardActions}><button className={s.secondary} disabled={busy||!status?.googleReady} onClick={google}>{status?.google?"Reconnect Google":"Connect Google Calendar"}</button>{status?.google&&<button className={s.textButton} disabled={busy} onClick={async()=>{setBusy(true);try{await apiRequest("/api/railwatch/connections",{method:"POST",body:JSON.stringify({googleEnabled:!status.google!.enabled})});setStatus({...status,google:{...status.google!,enabled:!status.google!.enabled}});notice("Calendar connection updated.");}catch(e){fail(e instanceof Error?e.message:"Could not update connection.");}finally{setBusy(false);}}}>{status.google.enabled?"Pause sync":"Resume sync"}</button>}</div></div>}</div><h3>Recent Reminder Activity</h3>{status?.jobs.length?status.jobs.map(job=><div className={s.fileRow} key={job.id}><span>{job.kind==="WHATSAPP"?"WhatsApp":"In-app"} reminder<small>{job.message}<br/>{job.sentAt?new Date(job.sentAt).toLocaleString():job.lastError}</small></span><span>{job.state==="SENT"?(job.kind==="WHATSAPP"?"Accepted by WhatsApp":"Available in RailWatch"):"Retrying"}</span></div>):<p className={s.help}>Reminder activity will appear here as booking dates approach.</p>}</section>;
}
