"use client";
import { useEffect,useState } from "react";
import { apiRequest } from "@/lib/client-api";
import { ActionMenu } from "./action-menu";
import s from "./planner.module.css";
type Data={health:{succeededAt:string|null;durationMs:number|null;exhausted:number;states:Record<string,number>;alerts:string[];providerFailures:Record<string,number>};jobs:{id:string;kind:string;state:string;dueAt:string;attempts:number;lastError:string|null;message:string;user:{name:string|null}}[];nextCursor:string|null};
/** Shows scheduler health and paginated missed/failed reminders with explicit retry actions. */
export function ReminderOperations({notice}:{notice:(message:string)=>void}) {
  const [data,setData]=useState<Data>(),[error,setError]=useState(""),[busy,setBusy]=useState(false),[cursor,setCursor]=useState<string>();
  /** Reloads the selected page without automatically issuing delivery requests. */
  async function load(page:string|null|undefined=cursor) {setBusy(true);setError("");try{setData(await apiRequest<Data>("/api/admin/operations"+(page?"?cursor="+encodeURIComponent(page):"")));setCursor(page??undefined);}catch(e){setError(e instanceof Error?e.message:"Could not load delivery health.");}finally{setBusy(false);}}
  useEffect(()=>{let live=true;apiRequest<Data>("/api/admin/operations").then(result=>{if(live)setData(result);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
  /** Confirms one external send and lets the scheduler recheck its current eligibility. */
  async function retry(id:string) {if(!confirm("Retry this reminder now? It may arrive late. If a provider accepted an earlier attempt before the connection failed, the recipient could receive it twice."))return;setBusy(true);setError("");try{const result=await apiRequest<{message:string}>("/api/admin/operations",{method:"POST",body:JSON.stringify({id})});notice(result.message);await load();}catch(e){setError(e instanceof Error?e.message:"Could not queue retry.");}finally{setBusy(false);}}
  const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(new Date(value))+" IST":"Not recorded yet";
  return <section className={s.settingsCard}><div className={s.sectionHead}><h2>Reminder Delivery & Recovery</h2><button className={s.secondary} disabled={busy} onClick={()=>void load()}>Refresh</button></div>{error&&<p role="alert" className={s.modalError}>{error}</p>}{!data?<p>Loading delivery health…</p>:<><dl className={s.operationStats}><div><dt>Last successful run</dt><dd>{date(data.health.succeededAt)}</dd></div><div><dt>Missed reminders</dt><dd>{data.health.states.MISSED??0}</dd></div><div><dt>Retries exhausted</dt><dd>{data.health.exhausted}</dd></div><div><dt>Waiting to send</dt><dd>{data.health.states.PENDING??0}</dd></div></dl>{Object.values(data.health.providerFailures).some(count=>count>0)&&<p className={s.help}>Unresolved channel failures: {Object.entries(data.health.providerFailures).filter(([,count])=>count>0).map(([kind,count])=>`${kind=== "PUSH"?"Device notifications":kind}: ${count}`).join(" · ")}</p>}{data.health.alerts.length>0&&<div className={s.operationAlerts} role="status"><h3>Needs attention</h3><ul>{data.health.alerts.map(alert=><li key={alert}>{alert}</li>)}</ul></div>}<p className={s.help}>Reminders more than 24 hours late are held for review. Recoverable schedules from the last 30 days appear here while their journeys still need action.</p><div className={s.operationRows}>{data.jobs.map(job=><article className={s.operationRow} key={job.id}><div><b>{job.user.name??"Account"} · {job.kind==="IN_APP"?"In-app":job.kind==="PUSH"?"Device notification":job.kind}</b><p>{job.state==="MISSED"?"Missed delivery window":job.attempts>=5?"Automatic retries exhausted":"Delivery failed"} · {date(job.dueAt)}</p><p>{job.message}</p><small>{job.lastError??"Delivery was unavailable."}</small></div><ActionMenu label={`Reminder actions ${job.id}`} disabled={busy} actions={[{label:"Retry reminder",onClick:()=>void retry(job.id)}]}/></article>)}</div>{!data.jobs.length&&<p>No missed or failed reminders.</p>}<div className={s.cardActions}>{cursor&&<button className={s.secondary} disabled={busy} onClick={()=>void load(null)}>First page</button>}{data.nextCursor&&<button className={s.secondary} disabled={busy} onClick={()=>void load(data.nextCursor!)}>Next page</button>}</div></>}</section>;
}
