"use client";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { ExternalLink,LogOut,Settings2,X } from "lucide-react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/client-api";
import s from "./planner.module.css";
export function Profile({name,onName,notice,fail}:{name:string;onName:(name:string)=>void;notice:(message:string)=>void;fail:(message:string)=>void}){
const router=useRouter(),root=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),passwordForm=useRef<HTMLFormElement>(null),trigger=useRef<HTMLButtonElement>(null);const [menu,setMenu]=useState(false),[drawer,setDrawer]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");const initial=Array.from(name.trim())[0]?.toLocaleUpperCase()??"?";
useEffect(()=>{if(!menu)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setMenu(false);};const escape=(e:KeyboardEvent)=>{if(e.key==="Escape")setMenu(false);};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",escape);};},[menu]);
useEffect(()=>{if(drawer)dialog.current?.showModal();else dialog.current?.close();},[drawer]);
function close(){passwordForm.current?.reset();setError("");setDrawer(false);trigger.current?.focus();}
async function save(e:FormEvent<HTMLFormElement>,password=false){e.preventDefault();const form=e.currentTarget,fields=new FormData(form);setError("");if(password&&fields.get("newPassword")!==fields.get("confirmPassword")){setError("The new passwords do not match.");return;}setBusy(true);try{const body=password?{currentPassword:fields.get("currentPassword"),newPassword:fields.get("newPassword")}: {name:fields.get("name")};const saved=await apiRequest<{name?:string}>("/api/railplan/profile",{method:"PATCH",body:JSON.stringify(body)});if(saved.name)onName(saved.name);if(password)form.reset();notice(password?"Password changed. Other sessions have been signed out.":"Your name has been updated.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save your changes.");}finally{setBusy(false);}}
return <div className={s.profile} ref={root}><button ref={trigger} className={`${s.avatar} ${s.profileButton}`} aria-label="Open Profile Menu" aria-haspopup="menu" aria-expanded={menu} title={name} onClick={()=>setMenu(!menu)}>{initial}</button>{menu&&<div className={s.profileMenu} role="menu"><div className={s.profileIdentity}>{name}</div><button role="menuitem" onClick={()=>{setMenu(false);setError("");setDrawer(true);}}><Settings2 size={16}/>User Settings</button><a role="menuitem" href="https://www.irctc.co.in/nget/train-search" target="_blank" rel="noreferrer"><ExternalLink size={16}/>Open IRCTC</a><button role="menuitem" onClick={async()=>{try{await apiRequest("/api/auth/logout",{method:"POST"});router.replace("/");router.refresh();}catch(e){fail(e instanceof Error?e.message:"Sign out failed.");}}}><LogOut size={16}/>Sign Out</button></div>}
<dialog className={s.profileDrawer} ref={dialog} aria-labelledby="profile-title" onCancel={close}><header><div><h2 id="profile-title">User Settings</h2><p>Manage your personal account.</p></div><button className={s.iconButton} aria-label="Close User Settings" onClick={close}><X size={20}/></button></header><div className={s.drawerBody}>{error&&<div className={s.modalError} role="alert">{error}</div>}<form onSubmit={e=>void save(e)}><h3>Profile</h3><label className={s.field}>Display Name<input name="name" defaultValue={name} key={name} required minLength={2} maxLength={120} autoComplete="name"/></label><button className={s.primary} disabled={busy}>Save Name</button></form><form ref={passwordForm} onSubmit={e=>void save(e,true)}><h3>Change Password</h3><p>Enter your current password to choose a new one.</p><label className={s.field}>Current Password<input type="password" name="currentPassword" required maxLength={128} autoComplete="current-password"/></label><label className={s.field}>New Password<input type="password" name="newPassword" required minLength={12} maxLength={128} autoComplete="new-password"/></label><label className={s.field}>Confirm New Password<input type="password" name="confirmPassword" required minLength={12} maxLength={128} autoComplete="new-password"/></label><small>Use at least 12 characters with uppercase, lowercase, number, and symbol.</small><button className={s.primary} disabled={busy}>Change Password</button><button type="button" className={s.textButton} disabled={busy} onClick={async()=>{setBusy(true);setError("");try{const profile=await apiRequest<{email:string}>("/api/railplan/profile");await apiRequest("/api/auth/forgot-password",{method:"POST",body:JSON.stringify({email:profile.email})});notice("If email delivery is configured, a password reset link will be sent.");}catch(e){setError(e instanceof Error?e.message:"Could not request a reset.");}finally{setBusy(false);}}}>Forgot Your Current Password?</button></form></div></dialog></div>;
}
