"use client";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { ExternalLink,LogOut,Settings2,X,UserRound,SlidersHorizontal,LockKeyhole,Plug } from "lucide-react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/client-api";
import type { UserProfile } from "@/lib/feature-policy";
import type { Planner } from "@/lib/travel-planner";
import { DEFAULT_CLOCK,REMINDER_KEYS } from "@/lib/travel-planner";
import { ReminderTimes,Weekdays,Field } from "./forms";
import { Toast } from "./toast";
import { Connections } from "./connections";
import s from "./planner.module.css";
const TABS=[{id:"profile",label:"Profile",icon:UserRound},{id:"preferences",label:"Preferences",icon:SlidersHorizontal},{id:"connections",label:"Connections",icon:Plug},{id:"security",label:"Security",icon:LockKeyhole}] as const;
export function Profile({account,planner,onProfile,commit,notice,fail,backup,restore,exportCalendar}:{account:UserProfile;planner:Planner;onProfile:(user:UserProfile)=>Promise<void>;commit:(planner:Planner,message:string)=>Promise<boolean>;notice:(message:string)=>void;fail:(message:string)=>void;backup:()=>void;restore:(file?:File)=>void;exportCalendar:()=>void}){
const router=useRouter(),root=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),passwordForm=useRef<HTMLFormElement>(null),trigger=useRef<HTMLButtonElement>(null);const [user,setUser]=useState(account),[menu,setMenu]=useState(false),[drawer,setDrawer]=useState(false),[tab,setTab]=useState<string>("profile"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState("");const policy=account.policy;const initial=Array.from(user.name.trim())[0]?.toLocaleUpperCase()??"?";
useEffect(()=>{if(!menu)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setMenu(false);};const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMenu(false);trigger.current?.focus();}};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",escape);};},[menu]);
useEffect(()=>{if(drawer){dialog.current?.showModal();if(dialog.current)dialog.current.scrollTop=0;}else dialog.current?.close();},[drawer]);
function feedback(message:string){setToast(message);notice(message);}
function close(){setToast("");dialog.current?.querySelectorAll<HTMLInputElement>('input[type="password"]').forEach(input=>{input.value="";});passwordForm.current?.reset();setError("");setDrawer(false);trigger.current?.focus();}
async function save(e:FormEvent<HTMLFormElement>,password=false){e.preventDefault();const form=e.currentTarget,fields=new FormData(form);setError("");if(password&&fields.get("newPassword")!==fields.get("confirmPassword")){setError("The new passwords do not match.");return;}setBusy(true);try{const body=password?{currentPassword:fields.get("currentPassword"),newPassword:fields.get("newPassword")}: {name:fields.get("name"),email:fields.get("email"),phoneNumber:fields.get("phoneNumber"),currentPassword:fields.get("currentPassword")};const saved=await apiRequest<UserProfile>("/api/railwatch/profile",{method:"PATCH",body:JSON.stringify(body)});setUser(saved);await onProfile(saved);form.reset();feedback(password?"Password changed. Other sessions have been signed out.":"Your profile has been updated.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save your changes.");}finally{setBusy(false);}}
async function preferences(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=new FormData(e.currentTarget);setBusy(true);setError("");const weekendDays=fields.getAll("weekendDays").map(Number);if(weekendDays.length>6){setError("Keep at least one working day for long-weekend planning.");setBusy(false);return;}try{await commit({...planner,settings:{...planner.settings,theme:fields.get("theme") as "light"|"dark",weekendDays,...(policy.remindersEnabled?{reminderTimes:fields.getAll("reminderTimes") as Planner["settings"]["reminderTimes"],reminderClock:Object.fromEntries(REMINDER_KEYS.map(k=>[k,String(fields.get("clock_"+k)??DEFAULT_CLOCK[k])])) as Planner["settings"]["reminderClock"]}:{})}},"Your preferences have been saved.");}finally{setBusy(false);}}
return <div className={s.profile} ref={root}><button ref={trigger} className={`${s.avatar} ${s.profileButton}`} aria-label="Open Profile Menu" aria-haspopup="menu" aria-expanded={menu} title={user.name} onClick={()=>setMenu(!menu)}>{initial}</button>{menu&&<div className={s.profileMenu} role="menu"><div className={s.profileIdentity}>{user.name}<small>{user.email}</small></div><button role="menuitem" onClick={()=>{setMenu(false);setError("");setTab("profile");setDrawer(true);}}><Settings2 size={16}/>User Settings</button><a role="menuitem" href="https://www.irctc.co.in/nget/train-search" target="_blank" rel="noreferrer"><ExternalLink size={16}/>Open IRCTC</a><button role="menuitem" onClick={async()=>{try{await apiRequest("/api/auth/logout",{method:"POST"});router.replace("/login");router.refresh();}catch(e){fail(e instanceof Error?e.message:"Sign out failed.");}}}><LogOut size={16}/>Sign Out</button></div>}
<dialog className={s.profileDrawer} ref={dialog} aria-labelledby="profile-title" onCancel={close}><header><div><h2 id="profile-title">User Settings</h2><p>Your profile, preferences, and account security.</p></div><button className={s.iconButton} aria-label="Close User Settings" onClick={close}><X size={20}/></button></header><div className={s.profileLayout}><nav className={s.profileTabs} role="tablist" aria-label="User Settings Tabs" aria-orientation="horizontal">{TABS.filter(t=>t.id!=="connections"||(policy.remindersEnabled&&policy.whatsappEnabled)||policy.googleCalendarEnabled).map(t=><button key={t.id} id={"tab-"+t.id} type="button" role="tab" aria-selected={tab===t.id} aria-controls={"panel-"+t.id} onClick={()=>{passwordForm.current?.reset();setError("");setTab(t.id);}}><t.icon size={17}/>{t.label}</button>)}</nav><div className={s.drawerBody} role="tabpanel" id={"panel-"+tab} aria-labelledby={"tab-"+tab}>{error&&<div className={s.modalError} role="alert">{error}</div>}
{tab==="profile"&&<form onSubmit={e=>void save(e)} key={user.name+user.email+user.phoneNumber}><h3>Personal Details</h3><p>Sign in with your email. Your username appears on your profile and dashboard.</p><div className={s.profileFields}><label className={s.field}>Username<input name="name" defaultValue={user.name} required minLength={2} maxLength={120} autoComplete="name"/></label><label className={s.field}>Email<input name="email" type="email" defaultValue={user.email} required maxLength={254} autoComplete="email"/></label><label className={s.field}>Phone Number<input name="phoneNumber" type="tel" defaultValue={user.phoneNumber} placeholder="+919876543210" maxLength={20} autoComplete="tel"/></label><label className={s.field}>Current Password<input type="password" name="currentPassword" maxLength={128} autoComplete="current-password" aria-label="Current Password"/><small>Required only when changing your email.</small></label></div><small>Your phone number is used for your WhatsApp reminders when that feature is enabled.</small><button className={s.primary} disabled={busy}>Save Profile</button></form>}
{tab==="preferences"&&<><form onSubmit={preferences}><h3>Personal Preferences</h3><Field label="Appearance"><select name="theme" defaultValue={planner.settings.theme}><option value="light">Light</option><option value="dark">Dark</option></select></Field><fieldset><legend>Your Regular Days Off</legend><Weekdays name="weekendDays" selected={planner.settings.weekendDays}/></fieldset><p>Booking opens {policy.bookingWindowDays} days before travel. This is managed by your administrator.</p>{policy.remindersEnabled&&<><h3>Default Booking Reminders</h3><p>Override these for an individual journey or routine. Times are IST.</p><ReminderTimes times={planner.settings.reminderTimes} clock={planner.settings.reminderClock}/></>}<button className={s.primary} disabled={busy}>Save Preferences</button></form><section><h3>Calendar & Backup</h3><div className={s.settingsActions}>{policy.calendarExportEnabled&&<button className={s.secondary} onClick={exportCalendar}>Export Calendar (.ics)</button>}<button className={s.secondary} onClick={backup}>Download Backup</button>{policy.ticketUploadsEnabled&&<Field label="Restore Backup"><input type="file" accept=".json,application/json" onChange={e=>{restore(e.target.files?.[0]);e.target.value="";}}/></Field>}</div></section></>}
{tab==="connections"&&<Connections planner={planner} commit={commit} notice={feedback} fail={setError} policy={policy}/>}
{tab==="security"&&<form ref={passwordForm} onSubmit={e=>void save(e,true)}><h3>Change Password</h3><p>Changing your password signs out your other sessions.</p><label className={s.field}>Current Password<input type="password" name="currentPassword" required maxLength={128} autoComplete="current-password"/></label><div className={s.profileFields}><label className={s.field}>New Password<input type="password" name="newPassword" required minLength={12} maxLength={128} autoComplete="new-password"/></label><label className={s.field}>Confirm New Password<input type="password" name="confirmPassword" required minLength={12} maxLength={128} autoComplete="new-password"/></label></div><small>Use at least 12 characters with uppercase, lowercase, number, and symbol.</small><button className={s.primary} disabled={busy}>Change Password</button><button type="button" className={s.textButton} disabled={busy} onClick={async()=>{setBusy(true);setError("");try{await apiRequest("/api/auth/forgot-password",{method:"POST",body:JSON.stringify({email:user.email})});feedback("If email delivery is configured, a password reset link will be sent.");}catch(e){setError(e instanceof Error?e.message:"Could not request a reset.");}finally{setBusy(false);}}}>Forgot Your Current Password?</button></form>}
</div></div>{drawer&&toast&&<Toast key={toast} message={toast} dismiss={()=>setToast("")}/>}</dialog></div>;
}
