"use client";
import { useEffect,useState,type FormEvent } from "react";
import { apiRequest } from "@/lib/client-api";
import type { providerSummary } from "@/lib/provider-config";
import { Field } from "./forms";
import s from "./planner.module.css";
type Summary=ReturnType<typeof providerSummary>;
export function ProviderSettings({notice}:{notice:(message:string)=>void}){
  const [config,setConfig]=useState<Summary>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let live=true;apiRequest<Summary>("/api/admin/providers").then(v=>{if(live)setConfig(v);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
  async function update(body:unknown,message:string){setBusy(true);setError("");try{setConfig(await apiRequest<Summary>("/api/admin/providers",{method:"PATCH",body:JSON.stringify(body)}));notice(message);return true;}catch(e){setError(e instanceof Error?e.message:"Could not save provider settings.");return false;}finally{setBusy(false);}}
  async function save(e:FormEvent<HTMLFormElement>,provider:"google"|"whatsapp"){
    e.preventDefault();const form=e.currentTarget,f=new FormData(form),value=(name:string)=>String(f.get(name)??"").trim();
    const fields=provider==="google"?{clientId:value("clientId"),...(value("clientSecret")?{clientSecret:value("clientSecret")}: {})}:{phoneNumberId:value("phoneNumberId"),apiVersion:value("apiVersion"),templateName:value("templateName"),language:value("language"),...(value("accessToken")?{accessToken:value("accessToken")}: {})};
    if(await update({[provider]:fields},provider==="google"?"Google configuration saved. Users may need to reconnect their accounts.":"WhatsApp configuration saved."))form.querySelectorAll<HTMLInputElement>('input[type="password"]').forEach(input=>{input.value="";});
  }
  return <div className={s.adminSettings}>{error&&<p className={s.modalError} role="alert">{error}</p>}<section className={s.settingsCard}><h2>App Integrations</h2><p className={s.help}>Configure the providers once for this RailWatch instance. Users connect their own Google account and choose whether to receive WhatsApp reminders.</p><p className={s.help}>Saving credentials makes them available immediately. Provider approval and permissions are completed in Google Cloud or Meta; saved credentials alone do not verify access.</p></section>{!config?<p>Loading integrations…</p>:<>
    <form className={s.settingsCard} onSubmit={e=>void save(e,"google")} key={"google"+config.google.clientId+config.google.secretStored}><h2>Google Calendar</h2><p className={s.help}>{config.google.configured?"Credentials are configured. Each user can connect through User Settings.":"Create a Web Application OAuth client in Google Cloud and enable the Calendar API."} Configure the consent screen and register the redirect URI below.</p><Field label="Redirect URI"><input readOnly value={config.google.redirectUri}/></Field><div className={s.formGrid}><Field label="Google Client ID"><input name="clientId" defaultValue={config.google.clientId} required maxLength={512} placeholder="Your client ID ending in .apps.googleusercontent.com"/></Field><Field label="Google Client Secret" hint={config.google.secretStored?"Saved securely. Leave empty to retain it.":"The secret stays on the server."}><input name="clientSecret" type="password" autoComplete="new-password" required={!config.google.secretStored} maxLength={4096}/></Field></div><p className={s.help}>RailWatch requests access to calendars it creates. Users grant permission on Google’s consent screen. Changing these credentials pauses existing connections; users reconnect and may get a new RailWatch calendar.</p><a className={s.textButton} href="https://developers.google.com/identity/protocols/oauth2/web-server" target="_blank" rel="noreferrer">Google OAuth Setup Guide</a><div className={s.cardActions}><button className={s.primary} disabled={busy}>Save Google Configuration</button>{config.google.secretStored&&<button type="button" className={s.secondary} disabled={busy} onClick={()=>void update({google:null},"Google configuration removed. Calendar sync is paused.")}>Remove Google Configuration</button>}</div></form>
    <form className={s.settingsCard} onSubmit={e=>void save(e,"whatsapp")} key={"whatsapp"+JSON.stringify(config.whatsapp)}><h2>WhatsApp</h2><p className={s.help}>Messages are sent from your WhatsApp Business sender to users who enable reminders. Users do not need a Meta developer account.</p><div className={s.formGrid}><Field label="Phone Number ID" hint="Meta's sender ID, not a user's phone number."><input name="phoneNumberId" defaultValue={config.whatsapp.phoneNumberId} required inputMode="numeric" pattern="[0-9]+" maxLength={30}/></Field><Field label="Graph API Version" hint="Use a supported version from your Meta API setup."><input name="apiVersion" defaultValue={config.whatsapp.apiVersion} required pattern="v[0-9]+\.[0-9]+" placeholder="vXX.0" maxLength={8}/></Field><Field label="Approved Template Name"><input name="templateName" defaultValue={config.whatsapp.templateName} required pattern="[a-z0-9_]+" maxLength={512}/></Field><Field label="Template Language"><input name="language" defaultValue={config.whatsapp.language} required placeholder="en or en_US" maxLength={10}/></Field></div><Field label="WhatsApp Access Token" hint={config.whatsapp.tokenStored?"Saved securely. Leave empty to retain it.":"Use a token authorized to send WhatsApp Business messages."}><input name="accessToken" type="password" autoComplete="new-password" required={!config.whatsapp.tokenStored} maxLength={4096}/></Field><p className={s.help}>The approved template must have three body parameters, in order: route, travel date, and booking-opening date/time. Users add their international phone number under Profile and enable reminders under Connections.</p><a className={s.textButton} href="https://developers.facebook.com/docs/whatsapp/cloud-api/overview" target="_blank" rel="noreferrer">Meta WhatsApp Setup Guide</a><div className={s.cardActions}><button className={s.primary} disabled={busy}>Save WhatsApp Configuration</button>{config.whatsapp.tokenStored&&<button type="button" className={s.secondary} disabled={busy} onClick={()=>void update({whatsapp:null},"WhatsApp configuration removed. WhatsApp delivery is paused.")}>Remove WhatsApp Configuration</button>}</div></form>
    </>}</div>;
}
