"use client";
import { Children, isValidElement, useEffect, useId, useRef, useState, type SelectHTMLAttributes, type ReactElement, type ChangeEvent, type ReactNode } from "react";
import { ChevronDown, Check } from "lucide-react";
import s from "./planner.module.css";
/** Builds the visible option label for the themed select control. */
function optionText(node:ReactNode):string{return Children.toArray(node).map(item=>isValidElement(item)?optionText((item as ReactElement<{children:ReactNode}>).props.children):String(item)).join("");}
type Option={value:string;label:string;disabled:boolean};
/** Implements an accessible themed option menu backed by native form values. */
export function Select({children,value,defaultValue,onChange,id,disabled,className,...props}:SelectHTMLAttributes<HTMLSelectElement>){
 const generatedId=useId();const controlId=id??generatedId;
 const options:Option[]=Children.toArray(children).filter(isValidElement).map(child=>{const p=(child as ReactElement<{value?:string|number;children:string;disabled?:boolean}>).props;return {value:String(p.value??p.children),label:optionText(p.children),disabled:Boolean(p.disabled)};});
 const [local,setLocal]=useState(String(defaultValue??options[0]?.value??"")),[open,setOpen]=useState(false),[active,setActive]=useState(0);const native=useRef<HTMLSelectElement>(null),root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);const selected=String(value??local);
 useEffect(()=>{const select=native.current;const sync=()=>setLocal(select?.value??"");select?.addEventListener("change",sync);return()=>select?.removeEventListener("change",sync);},[]);
 useEffect(()=>{const form=native.current?.form;const reset=()=>{setLocal(String(defaultValue??options[0]?.value??""));setOpen(false);};form?.addEventListener("reset",reset);return()=>form?.removeEventListener("reset",reset);},[defaultValue,options]);
 useEffect(()=>{if(!open)return;const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close);},[open]);
 useEffect(()=>{if(open)document.getElementById(`${controlId}-option-${active}`)?.scrollIntoView({block:"nearest"});},[open,active,controlId]);
  /** Selects an option, updates its native form value, and restores trigger focus. */
 function choose(index:number){const option=options[index];if(!option||option.disabled)return;setLocal(option.value);if(native.current){native.current.value=option.value;onChange?.({target:native.current,currentTarget:native.current} as ChangeEvent<HTMLSelectElement>);}setOpen(false);trigger.current?.focus();}
 return <div ref={root} className={s.selectRoot}><select {...props} disabled={disabled} ref={native} value={selected} onChange={onChange} aria-hidden="true" tabIndex={-1} className={s.hiddenSelect}>{children}</select><button ref={trigger} id={controlId} disabled={disabled} type="button" role="combobox" aria-label={props["aria-label"]} aria-describedby={props["aria-describedby"]} aria-expanded={open} aria-controls={`${controlId}-options`} aria-activedescendant={open?`${controlId}-option-${active}`:undefined} className={`${s.selectTrigger} ${className??""}`} onClick={()=>{setActive(Math.max(0,options.findIndex(o=>o.value===selected)));setOpen(!open);}} onKeyDown={e=>{if(e.key==="Tab"||e.key==="Escape"){if(e.key==="Escape"&&open){e.preventDefault();e.stopPropagation();}setOpen(false);return;}if(["ArrowDown","ArrowUp","Home","End"].includes(e.key)){e.preventDefault();setOpen(true);setActive(e.key==="Home"?0:e.key==="End"?options.length-1:Math.max(0,Math.min(options.length-1,(open?active:options.findIndex(o=>o.value===selected))+(e.key==="ArrowDown"?1:-1))));}if(e.key==="Enter"||e.key===" "){e.preventDefault();if(open)choose(active);else{setActive(Math.max(0,options.findIndex(o=>o.value===selected)));setOpen(true);}}}}><span>{options.find(o=>o.value===selected)?.label??selected}</span><ChevronDown size={16}/></button>{open&&<div id={`${controlId}-options`} role="listbox" className={s.selectOptions}>{options.map((o,i)=><button id={`${controlId}-option-${i}`} key={o.value} type="button" role="option" aria-selected={o.value===selected} disabled={o.disabled} tabIndex={-1} data-active={active===i} onPointerMove={()=>setActive(i)} onClick={()=>choose(i)}>{o.label}{o.value===selected&&<Check size={15}/>}</button>)}</div>}</div>;
}
