import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { build } from "esbuild";
const root = "src/backend/routes";
const files = [];
async function walk(path) {
  for (const entry of await readdir(path, { withFileTypes: true })) {
    if (entry.isDirectory()) await walk(`${path}/${entry.name}`);
    else if (entry.name === "route.ts") files.push(`${path}/${entry.name}`);
  }
}
await walk(root);
files.sort();
const imports = [], routes = [];
for (const [index, file] of files.entries()) {
  imports.push(`import * as r${index} from ${JSON.stringify("./" + file.slice("src/backend/".length).replace(/\.ts$/, ""))};`);
  const source = await readFile(file, "utf8");
  const path = "/api/" + file.slice(root.length + 1, -"/route.ts".length).replace(/\[([^\]]+)\]/g, ":$1");
  for (const match of source.matchAll(/export (?:async )?function (GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)\(/g)) {
    routes.push(`{ method: ${JSON.stringify(match[1])} as const, path: ${JSON.stringify(path)}, handler: r${index}.${match[1]} as Handler }`);
  }
}
await writeFile("src/backend/routes.generated.ts", `// Generated by scripts/build-backend.mjs.\n${imports.join("\n")}\ntype Handler = (request: Request, context: {params: Promise<Record<string,string>>}) => Response | Promise<Response>;\nexport const routes = [\n${routes.join(",\n")}\n];\n`);
if (!process.argv.includes("--routes-only")) {
  await mkdir("build/backend", { recursive: true });
  await build({ entryPoints: ["src/backend/server.ts"], outfile: "build/backend/server.mjs", bundle: true, platform: "node", target: "node24", format: "esm", packages: "external", sourcemap: true });
  await build({ entryPoints: ["src/backend/storage-rollback.ts"], outfile: "build/backend/storage-rollback.mjs", bundle: true, platform: "node", target: "node24", format: "esm", packages: "external", sourcemap: true });
}
