import {reminderJourneyId} from "@/lib/in-app-notifications";
import {storedPlanner} from "@/lib/workspace-storage";
import { dismissInAppReminder,unreadNotifications } from "@/lib/in-app-notifications";
import { getProviderConfiguration,googleConfigured,telegramConfigured,telegramLoginConfigured } from "@/lib/provider-config";
import { getDeliveryConfiguration } from "@/lib/settings";
import { getFeaturePolicy } from "@/lib/settings";
import { decryptSecret } from "@/lib/crypto";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { ApiError,assertSameOrigin,jsonData,parseJson,routeError } from "@/lib/http";
import { whatsappReady } from "@/lib/railwatch-providers";
import { googleReady } from "@/lib/railwatch-google";
/** Returns available providers, account connection state, and actionable notifications without credentials. */
export async function GET(request:Request){try{const user=await requireUser();const policy=await getFeaturePolicy(),config=await getProviderConfiguration();const telegram=await prisma.railTelegram.findUnique({where:{userId:user.id},select:{providerId:true,enabled:true,username:true,chatId:true,linkTokenHash:true,linkExpiresAt:true}});const telegramCurrent=telegram?.providerId===config.telegram?.id;const google=await prisma.railGoogle.findUnique({where:{userId:user.id},select:{enabled:true,syncedAt:true,lastError:true,calendarId:true}});const jobs=await prisma.railJob.findMany({where:{userId:user.id,state:{in:["SENT","FAILED","MISSED"]}},orderBy:{updatedAt:"desc"},take:20,select:{id:true,kind:true,state:true,sentAt:true,lastError:true,payload:true,readAt:true}});const unread=await prisma.railJob.findMany({where:{userId:user.id,readAt:null,OR:[{kind:"IN_APP",state:"SENT"},{kind:{in:["IN_APP","TELEGRAM","WHATSAPP","EMAIL","PUSH"]},state:{in:["FAILED","MISSED"]}}]},orderBy:[{dueAt:"asc"},{id:"asc"}],select:{id:true,kind:true,state:true,sentAt:true,lastError:true,payload:true,readAt:true}});const workspace=await prisma.railWorkspace.findUnique({where:{userId:user.id}});const now=new Date();const pauses=await prisma.railReminderPause.findMany({where:{userId:user.id,until:{gt:now}},select:{journeyId:true}});const notifications=policy.remindersEnabled?unreadNotifications(unread,workspace?(await storedPlanner(prisma,user.id,workspace,unread.map(j=>reminderJourneyId(j.payload)).filter((id):id is string=>Boolean(id)))).journeys:[],now,new Set(pauses.map(p=>p.journeyId))):[];return jsonData({emailReady:Boolean((await getDeliveryConfiguration()).smtpUrl),emailVerified:user.emailVerified,telegramPairingPending:Boolean(telegramCurrent&&telegram?.linkTokenHash&&telegram.linkExpiresAt&&telegram.linkExpiresAt>new Date()),telegramLoginReady:policy.telegramEnabled&&telegramLoginConfigured(config),telegramBotUsername:config.telegram?.botUsername??"",notifications:notifications.map(({payload,...job})=>{const details=JSON.parse(decryptSecret(payload)!);return {...job,...details,...(job.state==="MISSED"?{message:`A reminder was missed before it could be delivered. Check this journey. ${details.message??""}`} : job.state==="FAILED"?{message:`${job.kind==="TELEGRAM"?"Telegram":job.kind==="WHATSAPP"?"WhatsApp":job.kind==="EMAIL"?"Email":job.kind==="PUSH"?"Device notification":"In-app"} reminder delivery failed. Check your connection in User Settings. ${details.message??""}`}:{})};}),telegramReady:policy.telegramEnabled&&telegramConfigured(config),telegram:telegramCurrent&&telegram?.chatId?{enabled:telegram.enabled,username:telegram.username}:null,policy,whatsappReady:(await getFeaturePolicy()).whatsappEnabled&&await whatsappReady(),googleReady:(await getFeaturePolicy()).googleCalendarEnabled&&await googleReady(),google,jobs:jobs.map(({payload,...job})=>({...job,...(payload?JSON.parse(decryptSecret(payload)!):{})}))});}catch(e){return routeError(e,request);}}
/** Updates the account calendar preference or acknowledges a journey notification. */
export async function POST(request:Request){try{assertSameOrigin(request);const user=await requireUser();const input=await parseJson(request,z.union([z.object({googleEnabled:z.boolean()}),z.object({readId:z.string()})]));if("googleEnabled" in input&&!(await getFeaturePolicy()).googleCalendarEnabled)throw new ApiError(403,"Google Calendar is disabled by the administrator.","FEATURE_DISABLED");if("googleEnabled" in input&&input.googleEnabled){const config=await getProviderConfiguration();const connection=await prisma.railGoogle.findUnique({where:{userId:user.id}});if(!googleConfigured(config)||!connection||JSON.parse(decryptSecret(connection.tokens)!).providerId!==config.google?.id)throw new ApiError(400,"Reconnect Google Calendar before resuming sync.","GOOGLE_RECONNECT_REQUIRED");}if("googleEnabled" in input)await prisma.railGoogle.updateMany({where:{userId:user.id},data:{enabled:input.googleEnabled}});else await dismissInAppReminder(user.id,input.readId);return jsonData({saved:true});}catch(e){return routeError(e,request);}}
