import { dismissInAppReminder,unreadNotifications } from "@/lib/in-app-notifications";
import { decodeWorkspace } from "@/lib/railplan-store";
import { getProviderConfiguration,googleConfigured,telegramConfigured,telegramLoginConfigured } from "@/lib/provider-config";
import { getFeaturePolicy } from "@/lib/settings";
import { decryptSecret } from "@/lib/crypto";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { ApiError,assertSameOrigin,jsonData,parseJson,routeError } from "@/lib/http";
import { whatsappReady } from "@/lib/railplan-providers";
import { googleReady } from "@/lib/railplan-google";
export async function GET(request:Request){try{const user=await requireUser();const policy=await getFeaturePolicy(),config=await getProviderConfiguration();const telegram=await prisma.railTelegram.findUnique({where:{userId:user.id},select:{providerId:true,enabled:true,username:true,chatId:true,linkTokenHash:true,linkExpiresAt:true}});const telegramCurrent=telegram?.providerId===config.telegram?.id;const google=await prisma.railGoogle.findUnique({where:{userId:user.id},select:{enabled:true,syncedAt:true,lastError:true,calendarId:true}});const jobs=await prisma.railJob.findMany({where:{userId:user.id,state:{in:["SENT","FAILED"]}},orderBy:{updatedAt:"desc"},take:20,select:{id:true,kind:true,state:true,sentAt:true,lastError:true,payload:true,readAt:true}});const unread=await prisma.railJob.findMany({where:{userId:user.id,kind:"IN_APP",state:"SENT",readAt:null},orderBy:[{dueAt:"asc"},{id:"asc"}],select:{id:true,kind:true,state:true,sentAt:true,lastError:true,payload:true,readAt:true}});const workspace=await prisma.railWorkspace.findUnique({where:{userId:user.id}});const notifications=policy.remindersEnabled?unreadNotifications(unread,workspace?decodeWorkspace(workspace.payload).journeys:[]):[];return jsonData({telegramPairingPending:Boolean(telegramCurrent&&telegram?.linkTokenHash&&telegram.linkExpiresAt&&telegram.linkExpiresAt>new Date()),telegramLoginReady:policy.telegramEnabled&&telegramLoginConfigured(config),telegramBotUsername:config.telegram?.botUsername??"",notifications:notifications.map(({payload,...job})=>({...job,...JSON.parse(decryptSecret(payload)!)})),telegramReady:policy.telegramEnabled&&telegramConfigured(config),telegram:telegramCurrent&&telegram?.chatId?{enabled:telegram.enabled,username:telegram.username}:null,policy,whatsappReady:(await getFeaturePolicy()).whatsappEnabled&&await whatsappReady(),googleReady:(await getFeaturePolicy()).googleCalendarEnabled&&await googleReady(),google,jobs:jobs.map(({payload,...job})=>({...job,...(payload?JSON.parse(decryptSecret(payload)!):{})}))});}catch(e){return routeError(e,request);}}
export async function POST(request:Request){try{assertSameOrigin(request);const user=await requireUser();const input=await parseJson(request,z.union([z.object({googleEnabled:z.boolean()}),z.object({readId:z.string()})]));if("googleEnabled" in input&&!(await getFeaturePolicy()).googleCalendarEnabled)throw new ApiError(403,"Google Calendar is disabled by the administrator.","FEATURE_DISABLED");if("googleEnabled" in input&&input.googleEnabled){const config=await getProviderConfiguration();const connection=await prisma.railGoogle.findUnique({where:{userId:user.id}});if(!googleConfigured(config)||!connection||JSON.parse(decryptSecret(connection.tokens)!).providerId!==config.google?.id)throw new ApiError(400,"Reconnect Google Calendar before resuming sync.","GOOGLE_RECONNECT_REQUIRED");}if("googleEnabled" in input)await prisma.railGoogle.updateMany({where:{userId:user.id},data:{enabled:input.googleEnabled}});else await dismissInAppReminder(user.id,input.readId);return jsonData({saved:true});}catch(e){return routeError(e,request);}}
